apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: jaegertracing
  namespace: monitoring
spec:
  interval: 5m
  url: https://jaegertracing.github.io/helm-charts
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: jaeger
  namespace: monitoring
spec:
  interval: 5m
  chart:
    spec:
      chart: jaeger
      version: "3.3.0"
      sourceRef:
        kind: HelmRepository
        name: jaegertracing
        namespace: monitoring
  values:
    provisionDataStore:
      cassandra: false
      elasticsearch: false
    allInOne:
      enabled: true
    storage:
      type: memory
    agent:
      enabled: false
    collector:
      enabled: false
    query:
      enabled: false
