apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: opentelemetry
  namespace: monitoring
spec:
  interval: 5m
  url: https://open-telemetry.github.io/opentelemetry-helm-charts
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: opentelemetry-operator
  namespace: monitoring
spec:
  interval: 5m
  chart:
    spec:
      chart: opentelemetry-operator
      version: "0.71.0"
      sourceRef:
        kind: HelmRepository
        name: opentelemetry
        namespace: monitoring
  values:
    admissionWebhooks:
      certManager:
        enabled: false
    manager:
      collectorImage:
        repository: otel/opentelemetry-collector-contrib
