apiVersion: v1
kind: Service
metadata:
  name: kbot
  namespace: kbot
  labels:
    app: kbot
spec:
  ports:
  - port: 8080
    targetPort: 80
    protocol: TCP
    name: metrics
  selector:
    app.kubernetes.io/name: helm
