apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: fluent
  namespace: monitoring
spec:
  interval: 5m
  url: https://fluent.github.io/helm-charts
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: fluent-bit
  namespace: monitoring
spec:
  interval: 5m
  chart:
    spec:
      chart: fluent-bit
      version: "0.47.10"
      sourceRef:
        kind: HelmRepository
        name: fluent
        namespace: monitoring
  values:
    config:
      outputs: |
        [OUTPUT]
            Name loki
            Match *
            Host loki.monitoring.svc.cluster.local
            Port 3100
            Labels job=fluentbit
            auto_kubernetes_labels on
      filters: |
        [FILTER]
            Name kubernetes
            Match kube.*
            Merge_Log On
            Keep_Log Off
            K8S-Logging.Parser On
            K8S-Logging.Exclude On
